import 'package:incontext/core/utils/result.dart';
import 'package:incontext/features/context/domain/entities/thought_entity.dart';

class ContextEnhancementResult {
  const ContextEnhancementResult({
    required this.enhancedContent,
  });

  final String enhancedContent;
}

class DummyContextEnhancementService {
  const DummyContextEnhancementService();

  Future<Result<ContextEnhancementResult>> enhanceContext({
    required List<ThoughtEntity> thoughts,
  }) async {
    // Simulate API delay
    await Future.delayed(const Duration(seconds: 3));

    // Create dummy enhanced content
    final thoughtsText = thoughts.map((t) {
      if (t.type == ThoughtType.text) {
        return t.rawContent;
      } else {
        return t.transcript ?? '[Audio without transcript]';
      }
    }).join('\n\n');

    final enhanced = '''
# Refined Context

Based on ${thoughts.length} thought(s), here's a refined understanding:

$thoughtsText

## Summary
This is a dummy AI-enhanced context. In production, this would be generated by an LLM that:
- Clarifies ambiguous statements
- Resolves contradictions
- Adds structure and coherence
- Maintains the user's original intent

The context represents the canonical understanding of what the user is thinking about.
''';

    return Success(ContextEnhancementResult(enhancedContent: enhanced.trim()));
  }
}
