// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    final apiKey = dotenv.env['WEB_API_KEY'];
    final appId = dotenv.env['WEB_APP_ID'];
    final messagingSenderId = dotenv.env['WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['WEB_PROJECT_ID'];
    final authDomain = dotenv.env['WEB_AUTH_DOMAIN'];
    final storageBucket = dotenv.env['WEB_STORAGE_BUCKET'];

    if (apiKey == null ||
        appId == null ||
        messagingSenderId == null ||
        projectId == null) {
      throw Exception(
        'Web Firebase configuration is missing. Please add WEB_API_KEY, WEB_APP_ID, '
        'WEB_MESSAGING_SENDER_ID, and WEB_PROJECT_ID to your .env file.',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain ?? '$projectId.firebaseapp.com',
      storageBucket: storageBucket ?? '$projectId.firebasestorage.app',
    );
  }

  static FirebaseOptions get android {
    final apiKey = dotenv.env['ANDROID_API_KEY'];
    final appId = dotenv.env['ANDROID_APP_ID'];
    final messagingSenderId = dotenv.env['ANDROID_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['ANDROID_PROJECT_ID'];
    final storageBucket = dotenv.env['ANDROID_STORAGE_BUCKET'];

    if (apiKey == null ||
        appId == null ||
        messagingSenderId == null ||
        projectId == null) {
      throw Exception(
        'Android Firebase configuration is missing. Please add ANDROID_API_KEY, ANDROID_APP_ID, '
        'ANDROID_MESSAGING_SENDER_ID, and ANDROID_PROJECT_ID to your .env file.',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket ?? '$projectId.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    final apiKey = dotenv.env['IOS_API_KEY'];
    final appId = dotenv.env['IOS_APP_ID'];
    final messagingSenderId = dotenv.env['IOS_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['IOS_PROJECT_ID'];
    final storageBucket = dotenv.env['IOS_STORAGE_BUCKET'];
    final iosClientId = dotenv.env['IOS_CLIENT_ID'];
    final iosBundleId = dotenv.env['IOS_BUNDLE_ID'];

    if (apiKey == null ||
        appId == null ||
        messagingSenderId == null ||
        projectId == null) {
      throw Exception(
        'iOS Firebase configuration is missing. Please add IOS_API_KEY, IOS_APP_ID, '
        'IOS_MESSAGING_SENDER_ID, and IOS_PROJECT_ID to your .env file.',
      );
    }

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket ?? '$projectId.firebasestorage.app',
      iosClientId: iosClientId,
      iosBundleId: iosBundleId ?? 'com.in-context',
    );
  }
}
