// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: 'PLACEHOLDER_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'PLACEHOLDER_PROJECT_ID',
    authDomain: 'PLACEHOLDER_AUTH_DOMAIN',
    storageBucket: 'PLACEHOLDER_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvhbbV3SKeI5cWzrerKe7QRZ95QejIlGY',
    appId: '1:854546904017:android:7467172813414d1a5866f0',
    messagingSenderId: '854546904017',
    projectId: 'kairos-develop',
    storageBucket: 'kairos-develop.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? 'AIzaSyBHQqCvxLU5Pn5GaTjd4tKAgleCZNh15Is',
    appId: dotenv.env['IOS_APP_ID'] ?? '1:602139630898:ios:54ac413679724c75c28b2b',
    messagingSenderId: dotenv.env['IOS_MESSAGING_SENDER_ID'] ?? '602139630898',
    projectId: dotenv.env['IOS_PROJECT_ID'] ?? 'in-context-44e6c',
    storageBucket: dotenv.env['IOS_STORAGE_BUCKET'] ?? 'in-context-44e6c.firebasestorage.app',
    iosClientId: dotenv.env['IOS_CLIENT_ID'] ?? '602139630898-nucghdriilkt7ucqeuob9a7ucvk1cmvc.apps.googleusercontent.com',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? 'com.in-context',
  );

}